
services:
  pgdatabase:
    container_name: database
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=flights
    volumes:
      - flight_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "8080:80"
    depends_on:
      - pgdatabase
      
volumes:
  flight_data:
    name: flight_data
  pgadmin-data:
    name: pgadmin-data

    
